pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install') {
      steps {
        dir('fire-front') {
          bat 'node -v && npm -v'
          // package-lock.json이 fire-front 안에 있으면 ci 추천
          bat 'npm install'
          // 또는 lock이 있으면: bat 'npm ci'
        }
      }
    }

    stage('Build') {
      steps {
        dir('fire-front') {
          bat 'npm run build'
        }
      }
    }

    stage('Archive dist') {
      steps {
        dir('fire-front') {
          archiveArtifacts artifacts: 'dist/**', fingerprint: true
        }
      }
    }
  }
}
